#!/bin/bash
#SBATCH -t 06:00:00
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=12
#SBATCH -N 4
#SBATCH -J "aug-TZVP-MOLOPT-GTH-tier-2Sr"
#SBATCH -D ./
#SBATCH --account=pn36zo
#SBATCH --partition=micro

#module purge
module unload intel-oneapi-compilers
module unload intel-mkl

module load slurm_setup
module load gcc/11
module load python/3.7.11-base
module load openblas/0.3.18-gcc11
module load openmpi/3.1.6-gcc11
module load libxc/5.1.5-gcc11
module load eigen/3.4.0-gcc11


export OMP_NUM_THREADS=12
export I_MPI_PIN_CELL=core
export I_MPI_PIN_DOMAIN=omp:compact


rm cp2k.out
mpiexec -n $SLURM_NTASKS /hppfs/work/pn36zo/di38fab/cp2k/exe/Supermuc-foss/cp2k.psmp *inp >> cp2k.out
