#!/bin/bash
#SBATCH -t 02:00:00
#SBATCH --ntasks-per-node=4
#SBATCH -N 8
#SBATCH -J "VASPBi"
#SBATCH -D ./
#SBATCH --account=pn36zo
#SBATCH --partition=fat

#module purge
module unload intel-oneapi-compilers
module unload intel-mkl

module load slurm_setup
module load vasp/6.4.3

ulimit -s unlimited

#export OMP_NUM_THREADS=4
#export I_MPI_PIN_CELL=core
#export I_MPI_PIN_DOMAIN=omp:compact

vasp6 -n $SLURM_NTASKS -s ncl
