#!/bin/bash
#SBATCH -t 01:00:00
#SBATCH --ntasks-per-node=32
#SBATCH -c 4
#SBATCH -N 1
#SBATCH -J 1_MoS2_SOC40aug-SZV
#SBATCH --account=hpc-prf-coopfst
#SBATCH -p normal
##SBATCH -q express

export OMP_NUM_THREADS=4
export OMP_PLACES=cores
export OMP_PROC_BIND=true

module purge
module load chem/CP2K/2024.1-foss-2023b-gcc-openmpi-openblas-libgrpp

rm cp2k.out
srun /pc2/groups/hpc-prf-metdyn/metdyn02_Remi/cp2k/newcp2k/cp2k/exe/local/cp2k.pdbg *inp >> cp2k.out
